### ISSUE TITLE
No GPS fix

### ISSUE THREAD

**Issue by fortiko** [HabitatMap/AirCastingAndroidClient#11]
In the beginning of January, for a couple of days (perhaps since the last app update, not sure), I always got

```
Without a GPS fix you can't
map your session or contribute
it to the CrowdMap
```

Despite the warning, recording and submitting does still work (data gets send to the server, I can see it in the rake web server logs).

However, as expected, no data shows up in the web interface.

Did something change in the application related to GPS locks and coordinates?

**Comment by mheimbinder** [comment]
We're in the process of fixing the faulty location fix notification.  This will be completed by the end of the month when we release an update to the Play store.
