### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by Poussinou** [HabitatMap/AirCastingAndroidClient#15]
Hi,

Since this app is GNU GPL v3 licensed, are you considering the fact to add it to [F-Droid](https://f-droid.org/)? There is a strong community behind, and we already have a Request for this app [here](https://gitlab.com/fdroid/rfp/issues/404).

You can find some documentation [here](https://f-droid.org/docs/). Unfortunately, as you can see in the Request, we cannot accept `com.google.android.gms:play-services-location` which is proprietary software. Can this dependency be removed safely via a new build flavor in the gradle, or totally removed?

Otherwise, if you don't want to work on the inclusion of this app by yourself, would it be ok for you if someone else do it for you?

**Comment by PanderMusubi** [comment]
@mheimbinder @czorek Friendly reminder, are you fine by having this a included in the F-Droid app store?

**Comment by PanderMusubi** [comment]
Hope the questions from https://gitlab.com/fdroid/rfp/issues/404 can get answered.
