### ISSUE TITLE
installation does not work locally

### ISSUE THREAD

**Issue by ahmed-isi** [HabitatMap/AirCastingAndroidClient#25]
Hello,

I followed the instructions added in the install file to install the source code, but I found several problem:

I installed android development tools Android 2.3.1 (API v.9)
I installed maven V: 2.2.1 / 3.0.4 / 3.6.0, I installed the maven android plugin
git clone project
Run mvn install inside that repo to install all the android dependencies for maven

I get Error deployment: BUILD FAILURE
Failed to execute goal on project aircasting: Could not resolve dependencies for project pl.llp:aircasting:apk:1.5.2: The following artifacts could not be resolved: com.android.support:appcompat-v7:aar:25.3.1, com.android.support:support-v4:aar:25.3.1, com.android.support:design:aar:25.3.1, com.google.android.gms:play-services-location:aar:8.3.0, com.github.PhilJay:MPAndroidChart:jar:v3.0.2: Failure to find com.android.support:appcompat-v7:aar:25.3.1 in http://repo.maven.apache.org/maven2 was cached in the local repository, resolution will not be reattempted until the update interval of central has elapsed or updates are forced

I installed plugin SDK deployer, but this plugin does not support API version 9 which is an absolute version..

I installed the manually requested packages but i think theres an issue in linking files, issue at project level

You can help us ?

**Comment by mheimbinder** [comment]
Hello.  We need to update the instructions under "Developing".  We'll take
care of this in the next couple weeks.  In the meantime, please use Gradle
rather than Maven.

-Michael-

--------------------
Michael Heimbinder
Executive Director, HabitatMap
347.410.9499
www.habitatmap.org
www.aircasting.org
www.takingspace.org
twitter.com/habitatmap

**Comment by ahmed-isi** [comment]
we are going to buy an Airbeam sensor, and I need the installation instructions of the mobile app, for the Gradle you have the instructions to follow to install the app correctly ?
